server/db/db.js, server/db/models/category.js, server/db/models/index.js, server/db/models/product.js
=> product model

app/main.jsx, server/api/index.js, server/api/products.js
=> initial product routes

server/api/index.js, server/api/products.js, server/api/reviews.js, server/db/models/index.js, server/db/models/review.js
=> Review model routes

package-lock.json, server/api/index.js, server/api/users.js, server/api/users.spec.js, server/db/models/index.js, server/db/models/user.js
=> 10user model routes

client/components/main.js, client/components/products.js, client/store/products.js, client/store/singleProduct.js, public/index.html, public/style.css
=> component changes on wrong branch

package-lock.json, server/api/index.js, server/api/orders.js, server/api/purchases.js, server/db/models/index.js, server/db/models/order.js, server/db/models/purchase.js, server/index.js
=> 19purchase table

script/seed.js, server/api/index.js, server/api/orders.js, server/api/products.js, server/api/users.js
=> routes touched up, lookin fresh

client/routes.js
=> fixed some component routes, yo

client/components/admin.js, client/components/index.js, client/routes.js, client/store/index.js, client/store/orders.js, client/store/users.js, server/api/orders.js
=> 14 admin portal

client/components/cart.js, client/components/index.js, client/routes.js, client/store/cart.js, client/store/index.js
=> working cart reducer and component

client/components/cart.js, client/store/cart.js
=> fixed cart bug

client/components/cart.js, client/store/singleProduct.js, server/api/orders.js
=> testing fixes

client/components/main.js, package-lock.json, public/index.html
=> cdn added, started nav

client/components/checkout.js, server/api/orders.js
=> user id and select visable

client/index.js, package-lock.json, package.json, public/index.html
=> materialize ui

client/components/admin.js, client/components/products.js, package-lock.json, package.json
=> Styling misc updates

client/components/admin.js, client/index.scss
=> updated styling on admin page

client/components/main.js, client/index.scss, client/routes.js, public/index.html
=> working navbar, hamburger, and footer

client/components/main.js
=> fixed navbar and working hamburger

client/components/main.js
=> everyone sees cart badge

public/index.html
=> fixing twitter card

client/components/product-form.js, client/components/review-form.js, client/components/singleProduct.js, client/store/products.js, server/api/products.js
=> bug fixes for single product reviews
